JdyyDictURL = "/camel/rest/jdyy/dicts"
JdyyDictsTypesListURL = "/camel/rest/jdyy/dicts/types/list"

#图片上传
JdyyimgURL = "/camel/rest/jdyy/imgs"
#统计录入
JdyystatURL = "/camel/rest/jdyy/statisticss"
#病员信息
JdyypatientsURL = "/camel/rest/jdyy/patientss"
#术式
JdyysurURL = "/camel/rest/jdyy/surgicals"
#诊断
JdyydiaURL = "/camel/rest/jdyy/diagnosiss"
